# docker-compose.dev.yml
services:
  postgres:
    image: postgres:15
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quizgen-network

  # web:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
  #     - AUTH_URL=${AUTH_URL}
  #     - AUTH_SECRET=${AUTH_SECRET}
  #     - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
  #     - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
  #   volumes:
  #     - ./web:/app
  #     - /app/node_modules
  #     - /app/.next
  #   depends_on:
  #     - postgres
  #   networks:
  #     - quizgen-network

networks:
  quizgen-network:
    driver: bridge

volumes:
  postgres_data:
